name: Publish on dockerhub

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - dev
    paths-ignore:
      - '**.md'
    tags:
      - 'v*'
  release:
    types: [published]

# env:
#   REGISTRY_IMAGE: docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

jobs:

  release:
    uses: ./.github/workflows/job_dockerhub_publish.yml
    # with:
    #   ref: "v${{ needs.release.outputs.version }}"
    secrets: inherit  
    # secrets:
    #   DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
