name: Automatic Semantic Release

on:
  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        id: semantic-release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          verbosity: 1

      - name: Report release status
        if: steps.semantic-release.outputs.released == 'true'
        run: |
          echo "A new release was published!"
          echo "Release version: ${{ steps.semantic-release.outputs.version }}"


