name: Automatic Semantic Release

on:
  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    outputs:
      released: ${{ steps.semantic-release.outputs.released }}
      version: ${{ steps.semantic-release.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        id: semantic-release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          verbosity: 1

      - name: Report release status
        if: steps.semantic-release.outputs.released == 'true'
        run: |
          echo "A new release was published!"
          echo "Release version: ${{ steps.semantic-release.outputs.version }}"


  release-dockerhub:
    needs: release
    if: needs.release.outputs.released == 'true'
    uses: ./.github/workflows/ci.yml
    with:
      ref: ${{ needs.release.outputs.version }}

